---
- name: copy singageos.repo to /etc/yum.repos.d/singageos.repo
  copy:
    src: repos/signageos.repo
    dest: /etc/yum.repos.d/signageos.repo

- name: install singageos server
  ansible.builtin.dnf:
    name: signageos-fedora.x86_64
    state: present

- name: configure singageos server
  template:
    src: signageos.config.j2
    dest: /etc/signageos/singageos.conf
    owner: root
    group: root

- name: enable/start sinageos-server.service
  service:
    name: signageos-server
    enabled: true
    state: started
