---
- name: software | tailscale | repo
  ansible.builtin.copy:
    src: repos/tailscale.repo
    dest: /etc/yum.repos.d/tailscale.repo

- name: software | tailscale | install
  ansible.builtin.dnf:
    name: tailscale
    state: present

- name: software | tailscale | enable
  service:
    name: tailscaled
    state: started
    enabled: true

- name: software | tailscale | register
  command: |-
    tailscale up --login-server {{ tailscale_login_server }} --authkey {{ tailscale_auth_key }}
