---
volumes:
  tailscale:
  guacd_drive:
  guacd_record:
  postgres_init:
  postgres_data:

networks:
  tailscale:
    driver: bridge

services:
  tailscale:
    build: docker/tailscale
    container_name: tailscale
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_STATE_DIR: ${TS_STATE_DIR}
      TS_USERSPACE: ${TS_USERSPACE}
    networks:
      - tailscale
    volumes:
      - tailscale:${TS_STATE_DIR}
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module

  guacd:
    build: docker/guacamole/guacd
    container_name: guacd
    depends_on:
      - tailscale
    networks:
      - tailscale
    volumes:
      - guacd_drive:/drive:rw
      - guacd_record:/record:rw

  postgres:
    build: docker/guacamole/postgres
    container_name: postgres
    depends_on:
      - tailscale
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - tailscale
    volumes:
      - postgres_init:/docker-entrypoint.initdb.d:ro
      - postgres_data:/var/lib/postgresql/data:rw

  guacamole:
    build: docker/guacamole/guacamole
    container_name: guacamole
    depends_on:
      - tailscale
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    links:
      - guacd
    networks:
      - tailscale
    ports:
      - 8080:8080/tcp

  nebootxyz:
    build: docker/netbootxyz
    container_name: netbootxyz
    depends_on:
      - tailscale
    networks:
      - tailscale
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - MENU_VERSION=1.9.9  # optional
      # - PORT_RANGE=30000:30010  # optional
      # - SUBFOLDER=/  # optional
      - NGINX_PORT=80
      # - WEB_APP_PORT=3000  # optional
    volumes:
      - netbootxyz_config:/config
      - netbootxyz_assets:/assets
    ports:
      - 3000:3000
      # - 69:69/udp
      - 8080:80  # optional
    restart: unless-stopped
