---
volumes:
  netbootxyz_config:
  netbootxyz_assets:

networks:
  netboot_network:
    driver: bridge

services:
  ansible:
    build: docker/ansible
    network_mode: host
    container_name: ansible
    volumes:
      - .:/root/sos-provisioner
      - ~/.ssh:/root/.ssh

  dnsmasq:
    build: docker/dnsmasq
    container_name: dnsmasq
    networks:
      - netboot_network
    cap_add:
      - NET_ADMIN
    ports:
      - 67:67/udp
      - 69:69/udp
    volumes:
      - netbootxyz_assets:/var/lib/tftpboot
      - ./docker/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf

  nebootxyz:
    build: docker/netbootxyz
    container_name: netbootxyz
    networks:
      - netboot_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - MENU_VERSION=1.9.9  # optional
      # - PORT_RANGE=30000:30010  # optional
      # - SUBFOLDER=/  # optional
      - NGINX_PORT=80
      # - WEB_APP_PORT=3000  # optional
    volumes:
      - netbootxyz_config:/config
      - netbootxyz_assets:/assets
    ports:
      - 3000:3000
      # - 69:69/udp
      - 8080:80  # optional
    restart: unless-stopped
