---
- hosts: localhost
  become: true
  tags:
    - patcher
    - ubuntu
  roles:
    - patcher/ubuntu

- hosts: localhost
  become: true
  tags:
    - provision
    - ubuntu
    - official
  roles:
    - provision/ubuntu/sos-official
