---
- hosts: localhost
  become: true
  tasks:
    - tags:
        - never
        - patcher
      block:
        - name: patcher | ubuntu
          include_role:
            name: patcher/ubuntu
          tags:
            - never
            - ubuntu

        - name: patcher | fedora
          include_role:
            name: patcher/fedora
          tags:
            - never
            - fedora

        - name: patcher | rescue
          command: command -v asdf &> /dev/null
          tags:
            - never
            - rescue
      rescue:
        - mail:
            host: '{{ mailchimp_host }}'
            port: '{{ mailchimp_port }}'
            username: '{{ mailchimp_user }}'
            password: '{{ mailchimp_pass }}'
            to: '{{ mailchimp_to }}'
            from: '{{ mailchimp_from }}'
            subject: Ansible Role Execution Failed
            body: test
            secure: starttls

    - name: provision
      tags:
        - never
        - provision
      block:
        - name: provision | ubuntu | official
          tags:
            - never
            - ubuntu
            - official
          include_role:
            name: provision/ubuntu-official

        - name: provision | ubuntu | custom
          tags:
            - never
            - ubuntu
            - custom
          include_role:
            name: provision/ubuntu-custom

        - name: provision | fedora | official
          tags:
            - never
            - fedora
            - official
          include_role:
            name: provision/fedora-official

        - name: provision | fedora | custom
          tags:
            - never
            - fedora
            - custom
          include_role:
            name: provision/fedora-custom
