---
- hosts: localhost
  become: true
  tasks:
    - name: patcher | ubuntu
      include_role:
        name: patcher/ubuntu

    - name: provision | ubuntu | official
      include_role:
        name: provision/ubuntu/sos-official
