---
- hosts: localhost
  become: true
  tags:
    - patcher
    - ubuntu
  roles:
    - patcher/ubuntu

- hosts: localhost
  become: true
  tags:
    - provision
    - ubuntu
    - official
  roles:
    - provision/ubuntu/sos-official

# saving him for later, we need to get updated ansible for this guy to work
# rescue:
#   - mail:
#       host: '{{ mailchimp_host }}'
#       port: '{{ mailchimp_port }}'
#       username: '{{ mailchimp_user }}'
#       password: '{{ mailchimp_pass }}'
#       to: '{{ mailchimp_to }}'
#       from: '{{ mailchimp_from }}'
#       subject: Ansible Role Execution Failed
#       body: test
#       secure: starttls
