---
# - name: upgrade/update system
#   command: dnf upgrade --refresh

- name: copy singageos.repo to /etc/yum.repos.d/singageos.repo
  copy:
    src: signageos.repo
    dest: /etc/yum.repos.d/signageos.repo

#- name: install singageos repository
#  command: |
#    dnf config-manager addrepo --from-repofile=/etc/yum.repos.d/signageos.repo

- name: install singageos server
  command: dnf install -y signageos-fedora.x86_64

- name: install cage
  command: dnf install -y cage

- name: configure singageos server
  ansible.builtin.template:
    src: signageos.config.j2
    dest: /etc/signageos/singageos.conf
    owner: root
    group: root

- name: enable/start sinageos server
  ansible.builtin.service:
    name: signageos-server
    enabled: true
    state: started
