---
- name: system | codecs | rpmfusion | install
  community.general.rpm_ostree_pkg:
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts.distribution_version | regex_replace('\..*', '') }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts.distribution_version | regex_replace('\..*', '') }}.noarch.rpm
    state: present

- name: system | codecs | openh264 | install
  ansible.builtin.ini_file:
    path: /etc/yum.repos.d/fedora-cisco-openh264.repo
    section: fedora-cisco-openh264
    option: enabled
    value: '1'
    mode: '0644'

- name: system | codecs | intel-media-driver | install
  community.general.rpm_ostree_pkg:
    name: intel-media-driver
    state: present
