---
- name: software | pipewire | install
  community.general.rpm_ostree_pkg:
    name:
      - pipewire
      - pipewire-pulseaudio
      - pipewire-alsa
    state: present
    apply_live: true

# broken. come back and fix me
# - name: software | pipewire | service
#   become: true
#   become_user: '{{ user }}'
#   ansible.builtin.systemd_service:
#     name: '{{ item }}'
#     enabled: true
#     state: started
#     scope: user
#   loop:
#     - pipewire
#     - pipewire-pulse
