---
# TODO: move back to upstream script if/when fixed :3
# - name: download provisioner script
#   ansible.builtin.get_url:
#     url: https://linux-package-repository.signageos.io/ubuntu/provision.sh
#     dest: '{{ ansible_env.HOME }}/provision.sh'
#     mode: '0700'

- name: copy provisioner script
  copy:
    src: provision.sh
    dest: '{{ ansible_env.HOME }}/provision.sh'
    mode: '0700'

- name: run the provisioner script
  command: sudo {{ ansible_env.HOME }}/provision.sh 12345

- include_tasks: sos_audio_hack.yml
  tags: never audio-hack
