---

- name: update ubuntu packages
  command: sudo apt update -y

- name: upgrade ubuntu packages
  command: sudo apt upgrade -y

- name: ubuntu packages
  command: sudo apt upgrade -y

- name: remove update-notifier
  package:
    name: update-notifier
    state: absent

- name: download teamviewer
  ansible.builtin.get_url:
    url: https://download.teamviewer.com/download/linux/teamviewer-host_amd64.deb
    dest: '{{ ansible_env.HOME }}/teamviewer_amd64.deb'
  timeout: 60
  register: teamviewer_download
  until: teamviewer_download is succeeded
  retries: 5
  delay: 10

- name: install teamviewer
  shell: dpkg -i {{ ansible_env.HOME }}/teamviewer_amd64.deb || exit 0

- name: configure teamviewer
  copy:
    src: global.conf
    dest: /etc/teamviewer/global.conf

- name: disable idle screen turnoff
  command: gsettings set org.gnome.desktop.session idle-delay 0
  become_user: '{{ user }}'
  environment:
    DISPLAY: :0
    XDG_RUNTIME_DIR: /run/user/1000

- name: disable suspend on ac power
  remote_user: '{{ user }}'
  command: |
    gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
  become_user: '{{ user }}'
  environment:
    DISPLAY: :0
    XDG_RUNTIME_DIR: /run/user/1000

- name: disable suspend on battery
  remote_user: '{{ user }}'
  command: |
    gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing'
  become_user: '{{ user }}'
  environment:
    DISPLAY: :0
    XDG_RUNTIME_DIR: /run/user/1000

- name: get available power profiles
  command: powerprofilesctl list
  register: power_profiles
  changed_when: false

- name: set to performance mode if available
  command: powerprofilesctl set performance
  when: "'performance' in power_profiles.stdout"

- name: disable notifications
  command: |-
    gsettings set com.ubuntu.update-notifier no-show-notifications true

- include_tasks: pipewire.yml
