---
# SignageOS requires at least one user event for audio to work.
# the rest of this is a hack to get that very thing working
# by starting a puppeteer instance running the app and pressing
# key as if someone was there
# ---------------------------------------------------------------------
- name: software | signageos | download nodesource setup script
  shell: curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh

- name: software | signageos | run nodesource script
  shell: chmod +x nodesource_setup.sh && ./nodesource_setup.sh

- name: software | signageos | install nodejs
  package:
    name: nodejs

- name: software | audio-hack | install puppeteer
  copy:
    src: puppeteer
    dest: /srv/
    owner: '{{ user }}'
    group: '{{ user }}'

- name: software | audio-hack | install chromium script
  copy:
    src: chromium
    dest: /usr/bin/revel-chromium
    owner: root
    group: root
    mode: '0755'

- name: software | audio-hack | npm install puppeteer
  become: true
  become_user: '{{ user }}'
  command: npm --prefix /srv/puppeteer install

- name: software | audio-hack | npx install chrome
  become: true
  become_user: '{{ user }}'
  shell: yes | npx puppeteer install chrome

- name: software | audio-hack | copy/replace chromium.service
  template:
    src: chromium.service.j2
    dest: /etc/systemd/system/chromium.service

- name: chown /var/lib/chromium
  command: chown -R {{ user }}:{{ user }} /var/lib/chromium

- name: software | audio-hack | start services
  systemd_service:
    name: '{{ item }}'
    state: started
    enabled: true
  loop:
    - signageos-server.service
    - chromium.service
# ---------------------------------------------------------------------
