---

- name: create cage group
  group:
    name: cage
    state: present

- name: create cage user
  user:
    name: cage
    groups:
      - cage

- name: chown -R cage:cage /var/lib/chromium
  file:
    path: /var/lib/chromium
    owner: cage
    group: cage
    state: directory

- name: install custom waychromium script
  copy:
    src: services/chromium/waychromium
    dest: /usr/bin/waychromium
    mode: '0700'

- name: install custom chromium service
  copy:
    src: services/chromium/chromium.service
    dest: /etc/systemd/system/chromium.service
    mode: '0700'

- name: enable/start custom chromium.service
  service:
    name: chromium
    enabled: true
    state: started
