---

# install signageos and there dependencies
- include_tasks: software/signageos.yml
- include_tasks: software/codecs.yml

# - include_tasks: system/users.yml
# - include_tasks: desktop/cage.yml

# configure gnome to run xorg + install teamviewer
- include_tasks: desktop/gnome-xorg.yml
- include_tasks: software/teamviewer.yml
