---

# install signageos and there dependencies
- include_tasks: software/signageos.yml
- include_tasks: software/codecs.yml

# configure the system
- include_tasks: system/users.yml

# configure cage as our kiosk desktop
- include_tasks: desktop/cage.yml

# configure gnome as our support desktop
- include_tasks: desktop/gnome-xorg.yml
- include_tasks: software/teamviewer.yml
