---
- name: install dnf5
  command: dnf install -y python3-libdnf5
  register: dnf5
  changed_when: "'Nothing to do.' not in dnf5.stdout"

- include_tasks: config/gsettings.yml
- include_tasks: config/performance.yml

# he's still not working :(
# - include_tasks: software/tailscale.yml

- include_tasks: system/update.yml
- include_tasks: system/patcher.yml
- include_tasks: system/codecs.yml

- include_tasks: software/btop.ym
- include_tasks: software/neovim.yml
- include_tasks: software/ghostty.yml
- include_tasks: software/pavucontrol.yml
- include_tasks: software/wdisplays.yml

- include_tasks: software/wlr-randr.yml
- include_tasks: software/wlrctl.yml
- include_tasks: software/kanshi.yml

- include_tasks: software/signageos.yml
- include_tasks: software/river.yml
- include_tasks: system/sos-audio-hack.yml

- include_tasks: system/uninstall-gnome.yml

- name: reboot player
  ansible.builtin.reboot:
    reboot_timeout: 600
