---
- name: software | singageos | remove snap chromium
  shell: sudo snap remove chromium
  register: snap_chromium
  ignore_errors: true

- name: software | signageos | check snap chromium
  ansible.builtin.debug:
    msg: chromium snap removed successfully
  when: snap_chromium.rc == 0

- name: software | signageos | add upstream chromium
  apt_repository:
    repo: ppa:savoury1/chromium
    state: present
    update_cache: true

- name: software | signageos | fix broken packages
  command: apt install --fix-broken -y

- name: software | singageos | install chromium
  package:
    name: chromium-browser

- name: software | signageos | install curl
  package:
    name: curl

- name: software | signageos | download nodesource setup script
  shell: curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh

- name: software | signageos | run nodesource script
  shell: chmod +x nodesource_setup.sh && ./nodesource_setup.sh

- name: software | signageos | install nodejs
  package:
    name: nodejs

- name: software | signageos | install gpg key
  get_url:
    url: https://linux-package-repository.signageos.io/ubuntu/DEB-GPG-KEY-signageos
    dest: /usr/share/keyrings/signageos.asc

- name: software | signageos | install list file
  copy:
    src: signageos.list
    dest: /etc/apt/sources.list.d/signageos.list

- name: software | signageos | apt update
  command: apt update

- name: software | signageos | install server
  package:
    name: signageos-ubuntu

- name: software | signageos | configure server
  template:
    src: signageos.conf.j2
    dest: /etc/signageos/signageos.conf
