#!/bin/sh
export USER=revel
export PWD=$(pwd)
export DISTRO=$(awk -F= '/^ID=/{print $2}' /etc/os-release)

export ANSIBLE_VAULT_PASSWORD_FILE=/home/$USER/.vaultpass


export USB_VAULT_PATH=".vaultpass"
export USB_SSH_PATH=".ssh"

failed () {
    echo "Installation failed. Press Enter to exit."
    read
    exit 1
}

ubuntu () {
    sudo apt update
    sudo apt install -y software-properties-common
    sudo add-apt-repository -y --update ppa:ansible/ansible
    sudo apt install -y ansible git
}

setup () {
    case "$DISTRO" in
        'ubuntu') ubuntu;;
        *) echo "Unsupported Distro"; exit 1 ;;
    esac

    # install .vaultpass file from usb
    sudo cp ./.vaultpass /home/${USER}/.vaultpass
    sudo chmod -x /home/${USER}/.vaultpass

    # TODO: when we make the repo private
    # install .ssh keys from usb
    # if [ -d "$USB_SSH_PATH" ]; then
	#     cp ./.ssh /home/${USER}/.ssh
    #     chmod 700 /home/${USER}/.ssh
    #     chmod 600 /home/${USER}/.ssh/id_rsa
    #     chmod 644 /home/${USER}/.ssh/id_rsa.pub
    # else
    #     echo "'${USB_SSH_PATH}' folder not found."
    #     exit 1
    # fi
    
    # pull our ansible playbook from github
    ansible-pull -U https://github.com/Revel-Media-Group/sos-provisioner --tags all,audio-hack
}


setup || failed
echo 'Installation complete. Press Enter to exit.'
read
