#!/bin/sh
failed () {
	echo "Installation failed. Press Enter to exit."
	read REPLY
	exit 1
}

image () {
	IMG=$(find . -type f -name '*.img.gz' | head -n 1)
	DISK=$(lsblk -o NAME,SIZE -d \
		| sort -k2 -rh \
		| head -n 1 \
		| awk '{print "/dev/" $1}')
	sudo zcat $IMG | sudo dd of=$DISK bs=4M status=progress
}

efi () {
	CURR=$(sudo efibootmgr | grep "Boot.*\*")
	TARG=$(efibootmgr \
		| grep "Boot.*\*.*ubuntu.*" \
		| tail -n 1 | awk '{print $1}' \
		| sed 's/Boot//g')
	NEW_BOOT="$(echo $TARG \
		| sed 's/*$//g'),$(sudo efibootmgr \
		| grep "Boot.*\*" \
		| grep -Fv "$TARG" \
		| sed 's/Boot//g' \
		| awk '{print $1}' \
		| sed 's/*$//g' \
		| paste -sd, -)"
	sudo efibootmgr -o $NEW_BOOT
}

image || failed
efi || failed
sudo reboot
