#!/bin/sh

export USER=revel
export PWD=$(pwd)

export ANSIBLE_REPO_URL=https://github.com/Revel-Media-Group/sos-provisioner
export ANSIBLE_VAULT_PASSWORD_FILE=/home/$USER/.vaultpass


failed () {
    echo "Installation failed. Press Enter to exit."
    read REPLY
    exit 1
}

setup () {
    # install .vaultpass file from usb
    echo "Copying vaultpass file"
    sudo cp ./.vaultpass /home/${USER}/.vaultpass
    sudo chmod -x /home/${USER}/.vaultpass
    
    ansible-pull -U $ANSIBLE_REPO_URL playbooks/patcher/ubuntu.yml
}

setup || failed

echo "Installation Success. Press Enter to exit."
read REPLY
