#!/bin/sh

failed () {
    echo "Installation failed. Please grab dev to resolve issue."
    read REPLY
    exit 1
}

setup () {
    tmux new-session -s provisioning -d "sh ${PWD}/.install"
    tmux attach -t provisioning
}

setup || failed
