#!/bin/sh
# system options
export USER=revel
export DISTRO=$(awk -F= '/^ID=/{print $2}' /etc/os-release)
export PWD=$(pwd)

failed () {
    echo "Installation failed. Please grab dev to resolve issue."
    read REPLY
    exit 1
}

setup () {
    # install .vaultpass file from usb
    echo "Copying vaultpass file"
    cp ./.vaultpass /home/${USER}/.vaultpass
    chmod -x /home/${USER}/.vaultpass

    # TODO: when we make the repo private
    # install .ssh keys from usb
    # echo "Copying SSH keys file"
    # if [ -d "$USB_SSH_PATH" ]; then
	#     cp ./.ssh /home/${USER}/.ssh
    #     chmod 700 /home/${USER}/.ssh
    #     chmod 600 /home/${USER}/.ssh/id_rsa
    #     chmod 644 /home/${USER}/.ssh/id_rsa.pub
    # else
    #     echo "'${USB_SSH_PATH}' folder not found."
    #     exit 1
    # fi
    
    tmux new-session -s provisioning -d "sh ${PWD}/.install"
    tmux attach -t provisioning
}

setup || failed
