#!/bin/sh
# system options
export USER=revel
export DISTRO=$(awk -F= '/^ID=/{print $2}' /etc/os-release)
export PWD=$(pwd)

failed () {
    echo "Installation failed. Press Enter to exit."
    read REPLY
    exit 1
}

ubuntu () {
    sudo apt update
    sudo apt install -y software-properties-common
    sudo add-apt-repository -y --update ppa:ansible/ansible
    sudo apt install -y ansible git tmux
}

fedora () {
    sudo dnf install -y ansible tmux
    sudo systemctl enable --now sshd.service
}

setup () {
    case "$DISTRO" in
        'ubuntu') ubuntu ;;
        'fedora') fedora ;;
        *) echo "Unsupported Distro"; exit 1 ;;
    esac

    # install .vaultpass file from usb
    echo "Copying vaultpass file"
    sudo cp ./.vaultpass /home/${USER}/.vaultpass
    sudo chmod -x /home/${USER}/.vaultpass

    # TODO: when we make the repo private
    # install .ssh keys from usb
    # echo "Copying SSH keys file"
    # if [ -d "$USB_SSH_PATH" ]; then
	#     cp ./.ssh /home/${USER}/.ssh
    #     chmod 700 /home/${USER}/.ssh
    #     chmod 600 /home/${USER}/.ssh/id_rsa
    #     chmod 644 /home/${USER}/.ssh/id_rsa.pub
    # else
    #     echo "'${USB_SSH_PATH}' folder not found."
    #     exit 1
    # fi
    
    tmux new-session -s provisioning -d "sh ${PWD}/.install"
    tmux attach -t provisioning
}

setup || failed
