#!/bin/sh
riverctl map normal Super+Shift R spawn "sh ~/river/init"
riverctl map normal Super+Shift Q close
riverctl map normal Super+Shift E exit

# set rivertile layout generator
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 &

# tags
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal Super $i set-focused-tags $tags
done

# terminal for debugging 
riverctl map normal Super Return spawn ghostty

# audio and volume keybindings
riverctl map normal None XF86AudioRaiseVolume spawn 'pactl set-sink-volume @DEFAULT_SINK@ +5%'
riverctl map normal None XF86AudioLowerVolume spawn 'pactl set-sink-volume @DEFAULT_SINK@ -5%'
riverctl map normal None XF86AudioMute spawn "pactl set-sink-mute @DEFAULT_SINK@ toggle"

pactl set-sink-volume @DEFAULT_SINK@ 100%

# when your down 'B A D' with configuration

# B - browser
riverctl map normal Super B spawn "sh -c 'riverctl set-focused-tags $((1 << (2 - 1))) & chromium-browser'"
# A - audio
riverctl map normal Super A spawn "sh -c 'riverctl set-focused-tags $((1 << (3 - 1))) & pavucontrol'"
# D - display
riverctl map normal Super D spawn "sh -c 'riverctl set-focused-tags $((1 << (4 - 1))) & wdisplays'"

# T - terminal, for good measure
riverctl map normal Super T spawn "sh -c 'riverctl set-focused-tags $((1 << (5 - 1))) & ghostty'"

riverctl map normal Super R spawn "sh ~/river/reset"


# window rules
riverctl rule-add tags="chromium.signageos" tags=$((1 << (1 - 1)))
 
# 'B A D' window rules
riverctl rule-add tags="Chromium-browser" tags=$((1 << (2 - 1)))
riverctl rule-add tags="org.pulseaudio.pavucontrol" tags=$((1 << (3 - 1)))
riverctl rule-add tags="wdisplays" tags=$((1 << (4 - 1)))
riverctl rule-add tags="com.mitchellh.ghostty" tags=$((1 << (5 - 1)))

# hide cursor after 3000 ms
riverctl hide-cursor timeout 3000


# autostart all the things
kanshi &
