---
- name: add pipewire ppa
  apt_repository:
    repo: ppa:pipewire-debian/pipewire-upstream
    state: present
    update_cache: true

- name: install pipewire packages
  package:
    name:
      - gstreamer1.0-pipewire
      - libpipewire-0.3-0
      - libpipewire-0.3-dev
      - libpipewire-0.3-modules
      - libspa-0.2-bluetooth
      - libspa-0.2-dev
      - libspa-0.2-jack
      - libspa-0.2-modules
      - pipewire
      - pipewire-audio-client-libraries
      - pipewire-pulse
      - pipewire-media-session
      - pipewire-bin
      - pipewire-locales
      - pipewire-tests
    state: present
    update_cache: true

- name: remove pulseaudio
  package:
    name: pulseaudio
    state: absent

- name: setup pipewire services
  ansible.builtin.systemd:
    name:
      - wireplumber.service
      - pipewire.service
      - pipewire.socket
    user: '{{ user }}'
    state: started
    enabled: true
