---
- name: install ubuntu patcher
  become: true
  become_user: root
  ansible.builtin.cron:
    name: 2am nightly ubuntu patcher
    minute: 0
    hour: 2
    job: ansible-pull -U {{ ansible_repo_https }} --tags ubuntu

- include_tasks: config/gsettings.yml
- include_tasks: config/update-manager.yml
