---
- name: config | gsettings | install pip
  ansible.builtin.dnf:
    name: python3-pip
    state: present

- name: config | gsettings | pip install psutil
  become: true
  become_user: '{{ user }}'
  pip:
    name: psutil
    state: present

- name: config | gsettings | disable idle screen turnoff
  become: true
  become_user: '{{ user }}'
  community.general.dconf:
    key: /org/gnome/desktop/session/idle-delay
    value: uint32 0
    state: present

- name: config | gsettings | disable suspend on AC power
  become: true
  become_user: '{{ user }}'
  community.general.dconf:
    key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type
    value: "'nothing'"
    state: present

- name: config | gsettings | disable suspend on battery
  become: true
  become_user: '{{ user }}'
  community.general.dconf:
    key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type
    value: "'nothing'"
    state: present
