---
# WARNING: this is just a patch playbook for ubuntu. you should try to use the 
# official provisioner role instead for consistency sake
- hosts: all:localhost
  become: true
  remote_user: '{{ user }}'
  tasks:
    - name: software | pipewire | add upstream ppa
      apt_repository:
        repo: ppa:pipewire-debian/pipewire-upstream
        state: present
        update_cache: true

    - name: software | pipewire | install packages
      package:
        name:
          - gstreamer1.0-pipewire
          - libpipewire-0.3-0
          - libpipewire-0.3-dev
          - libpipewire-0.3-modules
          - libspa-0.2-bluetooth
          - libspa-0.2-dev
          - libspa-0.2-jack
          - libspa-0.2-modules
          - pipewire
          - wireplumber
          - pipewire-audio-client-libraries
          - pipewire-pulse
          - pipewire-media-session
          - pipewire-bin
          - pipewire-locales
          - pipewire-tests
        state: present
        update_cache: true

    - name: software | pipewire | remove pulseaudio
      package:
        name: pulseaudio
        state: absent

    - name: software | pipewire | enable services
      become: true
      become_user: '{{ user }}'
      systemd_service:
        name: '{{ item }}'
        state: started
        enabled: true
      loop:
        - wireplumber
        - pipewire

    - name: software | pipewire | set volume to 50%
      command: pactl set-sink-volume @DEFAULT_SINK@ 50%

    - name: config | gsettings | install pip
      package:
        name: python3-pip

    - name: config | gsettings | pip install psutil
      become: true
      become_user: '{{ user }}'
      pip:
        name: psutil
        state: present

    - name: config | gsettings | mute system sounds
      become: true
      become_user: '{{ user }}'
      community.general.dconf:
        key: /org/gnome/desktop/sound/event-sounds
        value: 'false'
        state: present

    - name: software | signageos | install puppeteer
      copy:
        src: puppeteer
        dest: /srv/
        owner: '{{ user }}'
        group: '{{ user }}'

    - name: software | signageos | install chromium script
      copy:
        src: chromium
        dest: /usr/bin/revel-chromium
        owner: root
        group: root
        mode: '0755'
    - name: software | signageos | npm install puppeteer
      become: true
      become_user: '{{ user }}'
      command: npm --prefix /srv/puppeteer install

    - name: software | signageos | npx install chrome
      become: true
      become_user: '{{ user }}'
      shell: yes | npx puppeteer install chrome

    - name: software | signageos | copy/replace chromium.service
      template:
        src: chromium.service.j2
        dest: /etc/systemd/system/chromium.service

    - name: chown /var/lib/chromium
      command: chown -R {{ user }}:{{ user }} /var/lib/chromium

    - name: software | signageos | start services
      become: true
      become_user: '{{ user }}'
      systemd_service:
        name: '{{ item }}'
        state: started
        enabled: true
      loop:
        - signageos-server.service
        - chromium.service
