---
- hosts: localhost
  become: true
  become_user: '{{ revel }}'
  tasks:
    - block:
        - name: run ubuntu patcher
          include_role: patcher/ubuntu
          tags:
            - never
            - ubuntu

        - name: run fedora patcher
          include_role: patcher/fedora
          tags:
            - never
            - fedora

        - name: test rescue operation
          command: command -v asdf &> /dev/null
          tags:
            - never
            - rescue
      rescue:
        - mail:
            host: '{{ mailchimp_host }}'
            port: '{{ mailchimp_port }}'
            username: '{{ mailchimp_user }}'
            password: '{{ mailchimp_pass }}'
            to: '{{ mailchimp_to }}'
            from: '{{ mailchimp_from }}'
            subject: Ansible Role Execution Failed
            body: test
            secure: starttls
