---

- name: add cage group
  ansible.builtin.group:
    name: cage
    state: present

- name: add cage user
  ansible.builtin.user:
    name: cage
    group: cage
    state: present

- name: chown -R cage:cage /var/lib/chromium
  file:
    path: /var/lib/chromium
    owner: cage
    group: cage
    state: directory
