---

- name: update ubuntu packages
  command: sudo apt update -y

- name: upgrade ubuntu packages
  command: sudo apt upgrade -y

- name: download teamviewer
  ansible.builtin.get_url:
    url: https://download.teamviewer.com/download/linux/teamviewer-host_amd64.deb
    dest: '{{ ansible_env.HOME }}/teamviewer_amd64.deb'

- name: install teamviewer
  shell: dpkg -i {{ ansible_env.HOME }}/teamviewer_amd64.deb || exit 0

- name: configure teamviewer
  copy:
    src: global.conf
    dest: /etc/teamviewer/global.conf

- name: disable idle screen turnoff
  remote_user: '{{ user }}'
  command: gsettings set org.gnome.desktop.session idle-delay 0

- name: disable suspend on ac power
  remote_user: '{{ user }}'
  command: |
    gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'

- name: disable suspend on battery
  remote_user: '{{ user }}'
  command: |
    gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing'

- name: set to performance mode
  command: powerprofilesctl set performance

- name: disable notifications
  command: |
    gsettings set com.ubuntu.update-notifier no-show-notifications true

# - name: download provisioner script
#   ansible.builtin.get_url:
#     url: https://linux-package-repository.signageos.io/ubuntu/provision.sh
#     dest: '{{ ansible_env.HOME }}/provision.sh'
#     mode: '0700'

- name: copy provisioner script
  copy:
    src: provision.sh
    dest: '{{ ansible_env.HOME }}/provision.sh'
    mode: '0700'

- name: run the provisioner script
  command: sudo {{ ansible_env.HOME }}/provision.sh 12345
